"""
Regression tests for outputs generated by the Snakemake test workflow.

These tests do not start Snakemake themselves. ``tests/run_tests.py`` first
generates the genome- and protein-mode outputs, then sets
``PROKANOTA_TEST_MODE`` and invokes this file. Keeping generation and
validation separate makes every scientific or structural expectation visible
as a normal pytest test.

The committed fixtures under ``tests/expected`` are used for exact regression
comparisons. Additional assertions document biological and file-format
invariants so readers can understand why particular output properties matter.
"""

from __future__ import annotations

import difflib
import os
from collections import Counter
from pathlib import Path

import pytest
import yaml

TEST_MODE = os.environ.get("PROKANOTA_TEST_MODE")
if TEST_MODE not in {"pyhmmer", "full"}:
    # A normal `pytest` invocation has not generated fresh workflow outputs.
    # Skipping here avoids accidentally validating stale files from an older run.
    pytest.skip(
        "workflow outputs are generated by tests/run_tests.py",
        allow_module_level=True,
    )

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
DATABASES_FULL = PACKAGE_ROOT / "tests" / "test-databases.yaml"
DATABASES_PYHMMER = PACKAGE_ROOT / "tests" / "test-pyhmmer.yaml"
INTERIM_DIR = PACKAGE_ROOT / "tests" / "output" / "interim"
RESULTS_DIR = PACKAGE_ROOT / "tests" / "output" / "results"
EXPECTED_DIR = PACKAGE_ROOT / "tests" / "expected"
SAMPLES = [
    "Pyrococcus_furiosus_DSM_3638-GCF_008245085",
    "Pyrococcus_furiosus_DSM_3638-GCF_008245085_protein",
]
GENOME_SAMPLE = SAMPLES[0]


# Load the same database registry selected by the runner. The selected database
# names determine which raw/parsed outputs must exist and which annotation
# columns are expected in pyhmmer-only versus full testing mode.
def load_databases(path: Path, enabled_only: bool = False) -> list[dict[str, object]]:
    data = yaml.safe_load(path.read_text())
    databases = data.get("databases") if isinstance(data, dict) else None
    if not isinstance(databases, list):
        raise ValueError(f"Invalid databases file {path}: missing databases list")
    return [
        database
        for database in databases
        if isinstance(database, dict)
        and (not enabled_only or database.get("enabled", True))
    ]


SELECTED_DATABASES = load_databases(
    DATABASES_FULL if TEST_MODE == "full" else DATABASES_PYHMMER,
    enabled_only=True,
)
ENABLED_DB_NAMES = [
    database["name"]
    for database in SELECTED_DATABASES
    if isinstance(database.get("name"), str)
]
ENABLED_DB_COLUMNS = {
    column["name"]
    for database in SELECTED_DATABASES
    for column in database.get("columns", [])
    if isinstance(column, dict) and isinstance(column.get("name"), str)
}
ALL_DB_COLUMNS = {
    column["name"]
    for database in load_databases(DATABASES_FULL)
    for column in database.get("columns", [])
    if isinstance(column, dict) and isinstance(column.get("name"), str)
}
SAMPLE_DATABASES = [
    (sample_id, database_name)
    for sample_id in SAMPLES
    for database_name in ENABLED_DB_NAMES
]


# Raw search tools do not all emit rows in a deterministic order. This helper
# parses, optionally filters, sorts, and serializes tables into a stable form
# before comparison. It prevents harmless row-order differences from masking
# genuine changes in columns or values.
def normalize_tsv(
    path: Path,
    sort_key_col: str | int = "gene_id",
    column_filter=None,
    delimiter: str = "\t",
    line_parser=None,
    has_header: bool = True,
) -> str:
    raw_lines = path.read_text().splitlines()
    data_lines = [
        line.strip() for line in raw_lines if line.strip() and not line.startswith("#")
    ]
    if not data_lines:
        return ""

    if line_parser is not None:
        rows = [line_parser(line) for line in data_lines]
    else:
        rows = [line.split(delimiter) for line in data_lines]

    if has_header:
        header_columns = rows[0]
        data_rows = rows[1:]
    else:
        header_columns = []
        data_rows = rows

    if column_filter is not None and header_columns:
        keep_indexes = column_filter(header_columns)
    else:
        keep_indexes = list(range(len(header_columns))) if header_columns else []

    if header_columns:
        filtered_header = [header_columns[index] for index in keep_indexes]
        rows_to_sort = [[row[index] for index in keep_indexes] for row in data_rows]
    else:
        filtered_header = []
        rows_to_sort = data_rows

    if not rows_to_sort:
        sorted_rows = []
    elif isinstance(sort_key_col, int):
        sort_index = min(sort_key_col, len(rows_to_sort[0]) - 1)
        sorted_rows = sorted(rows_to_sort, key=lambda row: row[sort_index])
    elif sort_key_col in filtered_header:
        sort_index = filtered_header.index(sort_key_col)
        sorted_rows = sorted(rows_to_sort, key=lambda row: row[sort_index])
    else:
        sorted_rows = sorted(rows_to_sort, key=lambda row: row[0])

    normalized_rows = ["\t".join(row) for row in sorted_rows]
    if filtered_header:
        return "\n".join(["\t".join(filtered_header), *normalized_rows]).strip()
    return "\n".join(normalized_rows).strip()


def normalize_tblout(path: Path) -> str:
    """
    Normalize PyHMMER's whitespace-delimited internal hit table.

    Unlike the other search tools, PyHMMER does not emit a conventional TSV,
    so rows are split on whitespace and sorted by the target gene identifier.
    """
    return normalize_tsv(
        path,
        sort_key_col=0,
        line_parser=lambda line: line.split(maxsplit=18),
        has_header=False,
    )


def normalize_annotation(path: Path) -> str:
    """
    Normalize a final annotation table for the active database test mode.

    Expected full-mode fixtures contain columns for every test database.
    During pyhmmer-only testing, columns belonging exclusively to disabled
    databases are removed before comparison; all shared biological columns
    and enabled PyHMMER columns are still compared exactly.
    """

    def column_filter(header_columns):
        return [
            index
            for index, column in enumerate(header_columns)
            if column in ENABLED_DB_COLUMNS or column not in ALL_DB_COLUMNS
        ]

    return normalize_tsv(
        path,
        sort_key_col="gene_id",
        column_filter=column_filter,
    )


def assert_files_equal(actual: Path, expected: Path, normalizer=None) -> None:
    """Compare a generated file with its committed regression fixture."""
    assert expected.exists(), f"Missing expected file: {expected}"
    assert actual.exists(), f"Missing generated file: {actual}"

    if normalizer is None:
        actual_text = actual.read_text(encoding="utf-8", errors="replace")
        expected_text = expected.read_text(encoding="utf-8", errors="replace")
    else:
        actual_text = normalizer(actual)
        expected_text = normalizer(expected)

    if actual_text != expected_text:
        diff = "\n".join(
            difflib.unified_diff(
                expected_text.splitlines(),
                actual_text.splitlines(),
                fromfile=str(expected),
                tofile=str(actual),
                lineterm="",
            )
        )
        pytest.fail(diff)


def assert_directories_equal(actual: Path, expected: Path, normalizer=None) -> None:
    """
    Compare directory structure and every contained output file.

    This catches missing outputs, unexpected extra outputs, and changes in
    file contents rather than checking only a few hand-picked records.
    """
    assert expected.exists(), f"Missing expected directory: {expected}"
    assert actual.exists(), f"Missing generated directory: {actual}"

    expected_files = {
        path.relative_to(expected) for path in expected.rglob("*") if path.is_file()
    }
    actual_files = {
        path.relative_to(actual) for path in actual.rglob("*") if path.is_file()
    }
    assert actual_files == expected_files, (
        f"Directory contents differ; missing={sorted(expected_files - actual_files)}, "
        f"extra={sorted(actual_files - expected_files)}"
    )

    for relative_path in sorted(expected_files):
        selected_normalizer = (
            normalizer
            if normalizer is not None and relative_path.suffix == ".tsv"
            else None
        )
        assert_files_equal(
            actual / relative_path,
            expected / relative_path,
            normalizer=selected_normalizer,
        )


def parse_fasta(path: Path) -> dict[str, str]:
    """Parse FASTA records by their first header token for cross-format checks."""
    assert path.exists(), f"Missing FASTA: {path}"
    records = {}
    current_id = None
    current_sequence = []
    for line in path.read_text().splitlines():
        if line.startswith(">"):
            if current_id is not None:
                records[current_id] = "".join(current_sequence)
            current_id = line[1:].split()[0]
            current_sequence = []
        elif line.strip():
            current_sequence.append(line.strip())
    if current_id is not None:
        records[current_id] = "".join(current_sequence)
    return records


def parse_gff_features(path: Path) -> list[list[str]]:
    """
    Parse GFF3 feature rows.

    Headers, comments, and any trailing embedded FASTA section are ignored.
    Every biological feature must have the nine columns required by GFF3.
    """
    assert path.exists(), f"Missing GFF: {path}"
    features = []
    for line in path.read_text().splitlines():
        if line.startswith("##FASTA") or line.startswith(">"):
            break
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split("\t")
        assert len(fields) == 9, f"Invalid GFF row in {path}: {line}"
        features.append(fields)
    return features


def parse_tsv_rows(path: Path) -> list[dict[str, str]]:
    """Load a tabular output into dictionaries keyed by the header names."""
    assert path.exists(), f"Missing TSV: {path}"
    lines = [line for line in path.read_text().splitlines() if line.strip()]
    if not lines:
        return []
    header = lines[0].split("\t")
    rows = []
    for line in lines[1:]:
        fields = line.split("\t")
        assert len(fields) == len(header), f"Invalid TSV row in {path}: {line}"
        rows.append(dict(zip(header, fields, strict=True)))
    return rows


def normalize_sequence(sequence: str) -> str:
    """Remove formatting whitespace and normalize reference sequences to uppercase."""
    return "".join(character for character in sequence if character.isalpha()).upper()


def extract_gbk_translation(path: Path, locus_tag: str) -> str:
    """
    Extract a possibly wrapped GenBank ``/translation`` qualifier.

    GenBank wraps long protein sequences over multiple indented lines, so the
    parser continues until the closing quote belonging to the requested locus.
    """
    lines = path.read_text().splitlines()
    for index, line in enumerate(lines):
        if f'/locus_tag="{locus_tag}"' not in line:
            continue
        for translation_index in range(index, len(lines)):
            translation_line = lines[translation_index]
            if '/translation="' not in translation_line:
                continue
            fragment = translation_line.split('/translation="', 1)[1]
            parts = [fragment]
            if '"' in fragment:
                return normalize_sequence(fragment.split('"', 1)[0])
            for continuation in lines[translation_index + 1 :]:
                chunk = continuation.strip()
                if '"' in chunk:
                    parts.append(chunk.split('"', 1)[0])
                    return normalize_sequence("".join(parts))
                parts.append(chunk)
        break
    return ""


# ---
# 1. Raw Search and Parsed Annotation Regression
# ---

# Search outputs are compared before and after parsing. The raw comparison
# detects changes in external-tool invocation or numerical results; the parsed
# comparison detects changes in filtering, top-hit selection, mapping joins,
# configured annotation columns, and readable numerical formatting.


@pytest.mark.parametrize(
    ("sample_id", "database_name"),
    SAMPLE_DATABASES,
    ids=[f"{sample}-{database}" for sample, database in SAMPLE_DATABASES],
)
def test_raw_search_output_matches_fixture(sample_id, database_name):
    """Verify each search backend reproduces its expected raw hit table."""
    filename = "hits.tblout" if database_name == "test_pyhmmer" else "hits.tsv"
    normalizer = normalize_tblout if database_name == "test_pyhmmer" else None
    assert_files_equal(
        INTERIM_DIR / sample_id / database_name / filename,
        EXPECTED_DIR / sample_id / database_name / filename,
        normalizer=normalizer,
    )


@pytest.mark.parametrize(
    ("sample_id", "database_name"),
    SAMPLE_DATABASES,
    ids=[f"{sample}-{database}" for sample, database in SAMPLE_DATABASES],
)
def test_parsed_annotation_matches_fixture(sample_id, database_name):
    """Verify filtered and mapped database annotations match their fixtures."""
    assert_files_equal(
        INTERIM_DIR / sample_id / database_name / "parsed_annotation.tsv",
        EXPECTED_DIR / sample_id / database_name / "parsed_annotation.tsv",
        normalizer=lambda path: normalize_tsv(path, sort_key_col="gene_id"),
    )


# ---
# 2. Complete Feature and Annotation Output Regression
# ---

# Directory-level comparisons deliberately cover every generated file. For
# genome input this includes the normalized genome, nucleotide/protein FASTA,
# GFF3, GenBank, feature TSV, RNA TSV, and CRISPR TSV. Protein mode is checked
# against its corresponding feature files and final annotation table.


@pytest.mark.parametrize("sample_id", SAMPLES)
def test_feature_outputs_match_fixtures(sample_id):
    """Verify all feature files and their directory structure exactly."""
    assert_directories_equal(
        RESULTS_DIR / sample_id / "features",
        EXPECTED_DIR / sample_id / "features",
    )


@pytest.mark.parametrize("sample_id", SAMPLES)
def test_annotation_outputs_match_fixtures(sample_id):
    """Verify each sample's complete final annotation table."""
    assert_directories_equal(
        RESULTS_DIR / sample_id / "annotation",
        EXPECTED_DIR / sample_id / "annotation",
        normalizer=normalize_annotation,
    )


# ---
# 3. Cross-Sample and Master-Table Contracts
# ---


def test_common_annotation_contains_all_sample_rows():
    """
    Verify that the common annotation table contains every sample row once.

    The master table is intended to be the row-wise collection of individual
    sample annotations; losing or duplicating rows would invalidate downstream
    comparative analyses.
    """
    common_rows = parse_tsv_rows(
        RESULTS_DIR / "common" / "annotation" / "finalAnnotation.tsv"
    )
    sample_rows = [
        row
        for sample_id in SAMPLES
        for row in parse_tsv_rows(
            RESULTS_DIR / sample_id / "annotation" / f"{sample_id}_finalAnnotation.tsv"
        )
    ]
    assert len(common_rows) == len(sample_rows)


def test_genome_and_protein_inputs_produce_same_proteins():
    """
    Verify genome prediction and direct protein import contain the same proteins.

    The protein fixture was derived from the genome-mode protein output. Matching
    sequence multiplicities, independent of record order and generated IDs,
    checks that the two input modes feed equivalent proteins into annotation.
    """
    genome_faa = RESULTS_DIR / SAMPLES[0] / "features" / f"{SAMPLES[0]}.faa"
    protein_faa = RESULTS_DIR / SAMPLES[1] / "features" / f"{SAMPLES[1]}.faa"
    assert Counter(parse_fasta(genome_faa).values()) == Counter(
        parse_fasta(protein_faa).values()
    )


# ---
# 4. GFF3 Structural Validation
# ---

# GFF3 uses one-based inclusive coordinates. Starts and ends must therefore be
# positive integers with start <= end. The strand column is restricted by the
# GFF3 format, and CRISPR repeat_region features are intentionally unstranded.


@pytest.mark.parametrize("sample_id", SAMPLES)
def test_gff_coordinates_are_valid(sample_id):
    """Verify that every GFF3 feature has a valid one-based interval."""
    gff_path = RESULTS_DIR / sample_id / "features" / f"{sample_id}.gff"
    for fields in parse_gff_features(gff_path):
        start = int(fields[3])
        end = int(fields[4])
        assert start >= 1 and end >= start


@pytest.mark.parametrize("sample_id", SAMPLES)
def test_gff_strands_are_valid(sample_id):
    """Verify GFF3 strand symbols and unstranded CRISPR regions."""
    gff_path = RESULTS_DIR / sample_id / "features" / f"{sample_id}.gff"
    for fields in parse_gff_features(gff_path):
        if fields[2] == "repeat_region":
            assert fields[6] == "."
        else:
            assert fields[6] in ("+", "-", ".", "?")


# ---
# 5. Specialized Biological Output Validation
# ---


def test_crispr_array_geometry_is_consistent():
    """
    Verify the internal geometry of every predicted CRISPR array.

    A biological CRISPR array must contain at least two repeats. Its reported
    length must equal the inclusive genomic interval, and that interval should
    be explained by the repeat lengths plus the intervening spacers. The small
    tolerance accounts for integer reporting of the average spacer length.
    """
    path = RESULTS_DIR / GENOME_SAMPLE / "features" / f"{GENOME_SAMPLE}_crispr.tsv"
    for row in parse_tsv_rows(path):
        start = int(row["start"])
        end = int(row["end"])
        length = int(row["length"])
        repeat_length = int(row["repeat_length"])
        spacer_length = int(row["spacer_length"])
        repeat_count = int(row["num_repeats"])

        assert repeat_count >= 2
        assert length == end - start + 1
        inferred_length = (repeat_count * repeat_length) + (
            (repeat_count - 1) * spacer_length
        )
        assert abs(length - inferred_length) <= repeat_count - 1


def test_reference_trna_records_are_present():
    """
    Validate tRNA records against known Pyrococcus furiosus loci.

    P. furiosus DSM 3638 contains the reference tRNA-His (NCBI Gene ID
    41713857) and tRNA-Cys (NCBI Gene ID 41713313) loci used below. The test
    checks their exact coordinates, strands, and nucleotide sequences, while
    also validating the naming and anticodon format of every predicted tRNA.
    """
    path = RESULTS_DIR / GENOME_SAMPLE / "features" / f"{GENOME_SAMPLE}_rna.tsv"
    rows = parse_tsv_rows(path)
    trna_rows = [row for row in rows if row["rna_type"].startswith("tRNA-")]

    for row in trna_rows:
        assert len(row["rna_type"]) >= 6
        assert row["rna_type"][5].isupper()
        if row["anti_codon"] != ".":
            assert len(row["anti_codon"]) == 3
            assert row["anti_codon"].islower()

    expected_records = [
        {
            "rna_type": "tRNA-His",
            "start": "1844790",
            "end": "1844866",
            "strand": "+",
            "sequence": "GCCGGGGTGGTGTAGCCTGGTTAGCACAGGGGACTGTGGATCCCCTGGCCCGGGTTCAAATCCCGGCCCCGGCCCCA",
        },
        {
            "rna_type": "tRNA-Cys",
            "start": "1380455",
            "end": "1380529",
            "strand": "-",
            "sequence": "GCCGGGATAGCCTAGAGGCCAGGCGGGGGACTGCAGATCCCCTTTACCCGGGTTCAAATCCCGGTCCCGGCTCCA",
        },
    ]
    for expected in expected_records:
        assert any(
            all(row[field] == value for field, value in expected.items())
            for row in trna_rows
        )


def test_reference_rrna_records_are_present():
    """
    Validate the two known P. furiosus 5S ribosomal RNA loci.

    Coordinates and sequences are based on NCBI Gene IDs 41713297 and
    41713504:
    https://www.ncbi.nlm.nih.gov/datasets/gene/41713297/
    https://www.ncbi.nlm.nih.gov/datasets/gene/41713504/
    """
    path = RESULTS_DIR / GENOME_SAMPLE / "features" / f"{GENOME_SAMPLE}_rna.tsv"
    rrna_rows = [row for row in parse_tsv_rows(path) if row["rna_type"] == "5S_rRNA"]
    assert len(rrna_rows) == 2

    expected_records = [
        {
            "start": "1370591",
            "end": "1370712",
            "strand": "+",
            "sequence": "TACGGCGGCCATAGCGGGGGGGCCACACCCGGTCTCATTTCGAACCCGGAAGTTAAGCCCCCCAGCGATCCCGGTTGTACTGCCCTCCGAGAGGGGGCGGGAAGCCGGGGACGCCGCCGGCC",
        },
        {
            "start": "1541199",
            "end": "1541319",
            "strand": "-",
            "sequence": "TACGGCGGCCATAGCGGGGGGCCACACCCGGTCTCATTTCGAACCCGGAAGTTAAGCCCCCCAGCGATCCCGGTTGTACTGCCCTCCGAGAGGGGGCGGGAAGCCGGGGACGCCGCCGGCC",
        },
    ]
    for expected in expected_records:
        assert any(
            all(row[field] == value for field, value in expected.items())
            for row in rrna_rows
        )


def test_reference_argonaute_record_is_consistent_across_outputs():
    """
    Validate the published Pyrococcus furiosus Argonaute (PfAgo) record.

    PfAgo is NCBI Gene ID 41712340 and UniProt Q8U3D2. NCBI reports the
    minus-strand CDS at 535964-538276 (2313 bp). The test checks that known
    locus, the expected arCOG03890 hit, and exact reference nucleotide/protein
    sequences across GFF3, TSV, GenBank, FNA, and FAA outputs.

    References:
    https://www.ncbi.nlm.nih.gov/datasets/gene/41712340/
    https://www.uniprot.org/uniprotkb/Q8U3D2/entry
    """
    feature_id = "BFDTYSCHFX_1_00524"
    expected_start = "535964"
    expected_end = "538276"
    expected_length = "2313"
    feature_dir = RESULTS_DIR / GENOME_SAMPLE / "features"

    # Exact expected nucleotide sequence of PfAgo (NCBI Gene ID: 41712340).
    # Keeping the sequence here makes the check independent of the committed
    # golden FAA/FNA files and documents the biological reference explicitly.
    expected_nucleotide = normalize_sequence(
        """
        ATGAAAGCGAAAGTTGTTATTAATCTGGTAAAGATAAATAAAAAAATAATTCCAGATAAAATATATGTAT
        ATAGGCTCTTTAATGACCCAGAGGAAGAACTTCAAAAAGAGGGATATTCTATTTATCGCCTTGCATATGA
        AAACGTTGGTATTGTTATTGATCCAGAGAATCTGATTATTGCCACCACAAAAGAGCTTGAATATGAGGGA
        GAATTTATTCCCGAGGGTGAAATATCATTCTCGGAATTGCGTAATGACTATCAGAGTAAACTTGTCTTAA
        GATTGTTGAAGGAGAATGGAATAGGTGAATATGAATTATCGAAACTTCTTAGGAAGTTTAGAAAACCAAA
        AACTTTTGGGGATTATAAGGTCATTCCAAGCGTTGAGATGAGTGTGATAAAGCATGATGAAGATTTTTAT
        TTAGTAATTCATATAATTCATCAAATACAATCAATGAAAACACTGTGGGAGCTTGTAAACAAAGACCCTA
        AAGAGCTTGAAGAGTTTTTAATGACTCACAAGGAAAATTTAATGCTGAAGGACATTGCGTCACCACTTAA
        AACTGTTTATAAGCCTTGCTTTGAAGAGTATACTAAAAAACCAAAACTTGATCATAATCAAGAAATAGTA
        AAGTACTGGTATAATTATCATATTGAAAGATATTGGAATACTCCAGAAGCTAAATTAGAGTTTTATAGAA
        AATTTGGCCAAGTTGATTTAAAACAACCTGCAATTCTAGCGAAATTTGCATCTAAAATAAAGAAAAACAA
        AAATTACAAGATATATCTCTTGCCCCAATTAGTTGTCCCAACTTATAACGCCGAACAATTAGAAAGTGAC
        GTGGCGAAAGAAATTTTAGAATATACAAAACTGATGCCAGAAGAACGTAAAGAGCTTTTAGAAAACATCC
        TTGCAGAAGTTGATAGTGACATTATAGACAAATCATTAAGTGAAATTGAAGTAGAAAAAATTGCACAAGA
        ATTGGAAAACAAAATAAGGGTTAGAGATGACAAAGGGAACAGTGTACCAATTTCTCAATTAAATGTTCAA
        AAATCTCAATTACTACTTTGGACGAATTATTCACGAAAATATCCAGTTATATTGCCTTATGAAGTTCCAG
        AAAAGTTCAGAAAAATACGGGAGATACCAATGTTTATAATTCTAGATTCAGGACTTCTTGCCGACATTCA
        AAATTTTGCAACTAATGAATTCAGGGAGTTAGTAAAGAGCATGTACTATAGTCTTGCCAAAAAATACAAT
        AGTCTTGCCAAAAAAGCAAGGTCAACAAATGAAATAGGATTACCCTTTTTAGACTTTCGTGGGAAAGAAA
        AGGTTATAACTGAAGATTTAAACTCTGACAAAGGTATTATAGAAGTTGTGGAGCAGGTATCTAGTTTCAT
        GAAAGGAAAAGAACTAGGCCTAGCCTTTATAGCTGCAAGAAATAAACTTTCATCTGAGAAGTTTGAGGAA
        ATTAAAAGGAGACTCTTTAATTTAAATGTAATATCTCAAGTGGTTAACGAAGATACTTTAAAAAATAAAA
        GAGACAAATACGATAGAAATCGACTTGATCTATTTGTCAGACACAACTTACTTTTTCAAGTATTATCTAA
        ACTTGGAGTAAAGTATTATGTGCTAGATTACAGGTTCAATTATGACTACATCATTGGAATTGATGTTGCT
        CCCATGAAGCGTTCTGAGGGATATATAGGTGGTAGTGCCGTAATGTTTGACTCTCAAGGTTACATACGAA
        AAATTGTCCCAATTAAAATTGGTGAACAAAGAGGAGAATCAGTTGACATGAATGAGTTTTTCAAAGAAAT
        GGTTGATAAATTTAAAGAGTTCAATATTAAGCTAGATAATAAGAAAATACTACTTCTAAGAGATGGAAGA
        ATTACTAATAACGAAGAAGAAGGGCTCAAGTATATTTCCGAGATGTTTGATATTGAGGTGGTCACGATGG
        ACGTGATAAAAAATCACCCTGTGAGAGCCTTTGCTAATATGAAAATGTACTTTAACCTAGGTGGTGCAAT
        ATACCTAATCCCCCATAAGCTCAAACAAGCTAAAGGAACACCAATACCAATAAAGTTAGCCAAAAAGAGG
        ATAATTAAGAATGGAAAAGTCGAGAAGCAGAGTATCACTAGACAGGACGTCTTAGATATCTTCATTTTAA
        CTCGTCTTAACTATGGGAGTATTTCTGCTGATATGCGGTTGCCAGCACCCGTTCACTATGCTCACAAGTT
        TGCAAATGCAATCAGAAATGAATGGAAAATAAAAGAAGAGTTCCTTGCTGAGGGATTTTTGTATTTTGTT
        TGA
        """
    )

    # Exact expected translation sequence of PfAgo (UniProt Q8U3D2).
    expected_protein = normalize_sequence(
        """
        MKAKVVINLVKINKKIIPDKIYVYRLFNDPEEELQKEGYSIYRLAYENVGIVIDPENLIIATTKELEYEG
        EFIPEGEISFSELRNDYQSKLVLRLLKENGIGEYELSKLLRKFRKPKTFGDYKVIPSVEMSVIKHDEDFY
        LVIHIIHQIQSMKTLWELVNKDPKELEEFLMTHKENLMLKDIASPLKTVYKPCFEEYTKKPKLDHNQEIV
        KYWYNYHIERYWNTPEAKLEFYRKFGQVDLKQPAILAKFASKIKKNKNYKIYLLPQLVVPTYNAEQLESD
        VAKEILEYTKLMPEERKELLENILAEVDSDIIDKSLSEIEVEKIAQELENKIRVRDDKGNSVPISQLNVQ
        KSQLLLWTNYSRKYPVILPYEVPEKFRKIREIPMFIILDSGLLADIQNFATNEFRELVKSMYYSLAKKYN
        SLAKKARSTNEIGLPFLDFRGKEKVITEDLNSDKGIIEVVEQVSSFMKGKELGLAFIAARNKLSSEKFEE
        IKRRLFNLNVISQVVNEDTLKNKRDKYDRNRLDLFVRHNLLFQVLSKLGVKYYVLDYRFNYDYIIGIDVA
        PMKRSEGYIGGSAVMFDSQGYIRKIVPIKIGEQRGESVDMNEFFKEMVDKFKEFNIKLDNKKILLLRDGR
        ITNNEEEGLKYISEMFDIEVVTMDVIKNHPVRAFANMKMYFNLGGAIYLIPHKLKQAKGTPIPIKLAKKR
        IIKNGKVEKQSITRQDVLDIFILTRLNYGSISADMRLPAPVHYAHKFANAIRNEWKIKEEFLAEGFLYFV
        """
    )

    # 1. GFF3 must contain the published CDS interval on the minus strand.
    gff_rows = parse_gff_features(feature_dir / f"{GENOME_SAMPLE}.gff")
    assert any(
        row[2] == "CDS"
        and row[3] == expected_start
        and row[4] == expected_end
        and row[6] == "-"
        and f"ID={feature_id}" in row[8]
        for row in gff_rows
    )

    # 2. The feature TSV must report the same coordinates and inclusive length.
    feature_rows = parse_tsv_rows(feature_dir / f"{GENOME_SAMPLE}.tsv")
    assert any(
        row["gene_id"] == feature_id
        and row["start"] == expected_start
        and row["end"] == expected_end
        and row["strand"] == "-"
        and row["gene_length"] == expected_length
        for row in feature_rows
    )

    # 3. The final annotation must retain the known arCOG03890 PfAgo hit.
    annotation_rows = parse_tsv_rows(
        RESULTS_DIR
        / GENOME_SAMPLE
        / "annotation"
        / f"{GENOME_SAMPLE}_finalAnnotation.tsv"
    )
    assert any(
        row["gene_id"] == feature_id
        and row["gene_length"] == expected_length
        and row["test_pyhmmer_hit"] == "arCOG03890"
        for row in annotation_rows
    )

    # 4. GenBank must encode the minus-strand location and stable locus tag.
    gbk_path = feature_dir / f"{GENOME_SAMPLE}.gbk"
    gbk_text = gbk_path.read_text()
    assert f"complement({expected_start}..{expected_end})" in gbk_text
    assert f'/locus_tag="{feature_id}"' in gbk_text

    # 5. FNA, FAA, and GenBank translation must each match the independent
    # published reference sequences, not merely agree with one another.
    nucleotide = normalize_sequence(
        parse_fasta(feature_dir / f"{GENOME_SAMPLE}.fna")[feature_id]
    )
    protein = normalize_sequence(
        parse_fasta(feature_dir / f"{GENOME_SAMPLE}.faa")[feature_id]
    )
    assert nucleotide == expected_nucleotide
    assert protein == expected_protein
    assert extract_gbk_translation(gbk_path, feature_id) == expected_protein
