global:
  metadata: "metadata.csv"
  databases: "databases.yaml"
  logs: "logs"
  interim: "interim"
  results: "results"

features:
  translation_table: 11
  meta: false
  run_rrna: true
  run_trna: true
  run_crispr: true
  minimum_gene_length: 90