name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11"
          cache: "pip"
      - run: python -m pip install pre-commit
      - run: pre-commit run --all-files

  tests-minimal:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install pytest
        run: python -m pip install --upgrade pip pytest PyYAML polars pandas

      - name: Run minimal tests
        run: python prokanota/tests/run_tests.py --mode minimal

  tests-full:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: snakemake
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=3.11
            -c conda-forge
            -c bioconda
            snakemake
            pandas
            pytest
            polars
            pyyaml

      - name: Install prokanota
        shell: bash -l {0}
        run: micromamba run -n snakemake python -m pip install .

      - name: Test prokanota installation
        shell: bash -l {0}
        run: micromamba run -n snakemake prokanota run --help

      - name: Run full tests
        shell: bash -l {0}
        run: micromamba run -n snakemake prokanota test-full
